---

sudo: required
dist: trusty 

language: python
python: 2.7

env:
  matrix:
  - ANSIBLE_VERSION=2.4.2.0  ANSIBLE_EXTRA_VARS=""


before_install:
- sudo apt-get update -qq
- sudo apt-get install systemd-services

install:
- pip install ansible==$ANSIBLE_VERSION

script:
- ansible-playbook -i "localhost," playbook.yml --extra-vars="${ANSIBLE_EXTRA_VARS}" --syntax-check
- ansible-playbook -i "localhost," playbook.yml --extra-vars="${ANSIBLE_EXTRA_VARS}" --connection=local --sudo
- >
  ansible-playbook -i "localhost," playbook.yml --extra-vars="${ANSIBLE_EXTRA_VARS}" --connection=local --sudo
  | grep -q 'changed=0.*failed=0'
  && (echo 'Idempotence test: pass' && exit 0)
  || (echo 'Idempotence test: fail' && exit 1)
